# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to any branch. 
# For real use you might want to restrict this to the "prod" branch.
#
# define the name of our workflow
name: Delete microservice

# define triggers for the workflow, with push and manually triggering
on:
  #
  # only allows delete to be invoked manually
  #
  workflow_dispatch: 

# define one job for the workflow
jobs:

  # define the os for the job to run on
  deploy:
    runs-on: ubuntu-latest
    
    # define the environment variables for the job
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Delete
        run: ./scripts/delete.sh
